### ISSUE TITLE
Laravel 5 support

### ISSUE THREAD

**Issue by flinux** [Riari/laravel-forum#1]
As **Laravel 5** is now official and stable, *riari/laravel-forum* will become compatible with **L5** ?
I've tried to install it but after **composer update** I have exception:

```
exception 'BadMethodCallException' with message 'Call to undefined method [package]' in /home/linux/PhpstormProjects/webapp/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:226
Stack trace:
#0 /home/linux/PhpstormProjects/webapp/vendor/riari/laravel-forum/src/Riari/Forum/ForumServiceProvider.php(24): Illuminate\Support\ServiceProvider->__call('package', Array)
#1 /home/linux/PhpstormProjects/webapp/vendor/riari/laravel-forum/src/Riari/Forum/ForumServiceProvider.php(24): Riari\Forum\ForumServiceProvider->package('riari/laravel-f...', 'forum')
#2 [internal function]: Riari\Forum\ForumServiceProvider->boot()
#3 /home/linux/PhpstormProjects/webapp/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#4 /home/linux/PhpstormProjects/webapp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(631): Illuminate\Container\Container->call(Array)
#5 /home/linux/PhpstormProjects/webapp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(613): Illuminate\Foundation\Application->bootProvider(Object(Riari\Forum\ForumServiceProvider))
#6 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Riari\Forum\ForumServiceProvider), 21)
#7 /home/linux/PhpstormProjects/webapp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(614): array_walk(Array, Object(Closure))
#8 /home/linux/PhpstormProjects/webapp/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(15): Illuminate\Foundation\Application->boot()
#9 /home/linux/PhpstormProjects/webapp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(165): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#10 /home/linux/PhpstormProjects/webapp/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(192): Illuminate\Foundation\Application->bootstrapWith(Array)
#11 /home/linux/PhpstormProjects/webapp/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(89): Illuminate\Foundation\Console\Kernel->bootstrap()
#12 /home/linux/PhpstormProjects/webapp/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main}
```

**Comment by Riari** [comment]
I plan to add L5 support very soon. Will update here when I make progress :)

**Comment by Riari** [comment]
Sorry for the wait. I've added rudimentary Laravel 5 support via https://github.com/morrislaptop/LaravelFivePackageBridges - refer to the updated [readme](https://github.com/Riari/laravel-forum/blob/master/readme.md) for details.

If you try it, please let me know if you have any difficulties!

**Comment by Riari** [comment]
I've decided to do this a little differently to how I originally planned. Please bear with me and I'll update here soon with my progress :)

**Comment by Riari** [comment]
Really sorry for the wait, but I've just finished an initial conversion of the package to L5. You can find it in the [laravel-5 branch](https://github.com/Riari/laravel-forum/tree/laravel-5).

It looks like the lang files might not be loading correctly, but it should be functional aside from that. If you try it, please report any issues you come across :) thanks!
